name: Build InsightNote App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: InsightNote-windows
          path: dist/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build AppImage
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload .AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: InsightNote-linux
          path: dist/*

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS .app and .dmg
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload .dmg/.app artifact
        uses: actions/upload-artifact@v4
        with:
          name: InsightNote-macos
          path: dist/*
