name: Build SystemMuse App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build .exe for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed systemmuse.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: SystemMuse-Windows
          path: dist/systemmuse.exe

  build-linux:
    name: Build .AppImage for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libnss3
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build AppImage
        run: |
          pyinstaller --onefile --windowed systemmuse.py

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: SystemMuse-Linux
          path: dist/systemmuse

  build-macos:
    name: Build .dmg for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pyinstaller

      - name: Build .dmg
        run: |
          pyinstaller --onefile --windowed systemmuse.py

      - name: Upload macOS dmg
        uses: actions/upload-artifact@v3
        with:
          name: SystemMuse-macOS
          path: dist/systemmuse
